<h1>All Posts</h1>
<?php if (Session::getInstance()->isLoggedIn()): ?>
    <h3>What's on your mind?</h3>
    <form method="post" action="<?php echo App::config('url') ?>Index/newPost">
        <div class="input-group input-group-rounded">
            <input class="input-group-field" id="content" name="content">
            <div class="input-group-button">
                <button type="submit" class="button secondary">Save</button>
            </div>
        </div>
    </form>
<?php endif; ?>


<?php foreach ($posts as $post): ?>
    <a>
        <p>
            <img src="/app/images/<?= $post->getUserEmail() . '/' . $post->getUserImage() ?>" class="postImage">
            <b><?php echo htmlspecialchars($post->getUser()) ?></b>
            <a class="indent" href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
                <?= htmlspecialchars($post->getContent()) ?> </a> <br/>

            <?php if (Session::getInstance()->isLoggedIn()): ?>
                <a href="<?php echo App::config('url') ?>admin/like/<?php echo $post->id ?>">Like</a>
            <?php endif; ?>
            <cite>
                <?php echo 'Before ' . Post::countTime($post->date);
                if ($post->getLikes() > 0) {
                    echo $post->getLikes();
                    ?>
                    <a href="javascript:void(0);" data-open="likeModal">
                        <?= ($post->getLikes() != 1) ? ' likes' : ' like'; ?>
                    </a>
                    <?php
                }
                ?>
            </cite>
            <?php
            foreach ($post->getComments() as $comment): ?>
            <div class="indent">
        <p>
            <cite><?= htmlspecialchars($comment->user) ?></cite>
            <?php echo $comment->date ?><br/>
            <?php echo $comment->content ?>
        </p>
        <?php if (Session::getInstance()->isLoggedIn()): ?>
            <a href="javascript:void(0);" class="comForm">Comment</a>
            <form method="post" action="<?= App::config('url') ?>admin/commentComment/<?php echo $comment->id ?>"
                  class="form-horizontal showActionComment">
                <input type="text" name="content">
            </form>
        <?php endif; ?>
        <?php Comment::recursion($comment->id) ?>
        </div>
        <?php endforeach; ?>
        </p>
    </a>
<?php endforeach; ?>


<div class="reveal" id="likeModal" data-reveal>
    <h1>Login</h1>
    <?php echo $message ?>
    <?php foreach (Like::likes($post->id) as $like): ?>
        <?php echo $like->user ?>


    <?php endforeach; ?>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
