<form method="post" action="<?php echo App::config('url') ?>Index/newPost">
    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

<?php foreach ($posts as $post): ?>
    <p>
        <?php $date = date_create($post->getDateCreated()); echo $date->format('d-m-Y H:i') ?>
        <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
            <?= htmlspecialchars($post->getContent()) ?>
        </a>
    </p>
    <?php if(!empty($post->getImage())){ ?>
    <img src="app/images/<?= $post->getImage() ?>" height="50" width="50">
        <?php } ?>
<hr>
<?php endforeach; ?>