<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inchoo PHP Academy 2019</title>
    <link rel="stylesheet" type="text/css" href="/style/css/foundation.css">
    <link rel="stylesheet" type="text/css" href="/style/css/app.css">
</head>
<body>
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Inchoo PHP Academy 2019</li>
            <li><a href="<?php echo App::config('url') ?>Index/index">Home</a></li>
            <?php if (!Session::getInstance()->isLoggedIn()): ?>
                <a href="<?php echo App::config("url") . "admin/login" ?>">Login</a>
                <a href="<?php echo App::config("url") . "admin/registration" ?>">Registration</a>
            <?php else: ?>
                <a href="<?php echo App::config("url") . "admin/logout" ?>">Logout <?php echo Session::getInstance()->getUser()->name ?></a>
            <?php endif; ?>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Search"></li>
            <li><button type="button" class="button">Search</button></li>
        </ul>
    </div>
</div>
    <?php echo $content ?>

<script src="/style/js/vendor/jquery.js"></script>
<script src="/style/js/vendor/what-input.js"></script>
<script src="/style/js/vendor/foundation.js"></script>
<script src="/style/js/app.js"></script>
</body>
</html>