<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inchoo PHP Academy 2019</title>
    <link rel="stylesheet" href="style/css/foundation.css">
    <link rel="stylesheet" href="style/css/app.css">
</head>
<body>
    <?php echo $content ?>
</body>
<script src="style/js/vendor/jquery.js"></script>
<script src="style/js/vendor/what-input.js"></script>
<script src="style/js/vendor/foundation.js"></script>
</html>