

<?php echo $message ?>

<form method="post" action="<?php echo App::config('url') ?>admin/authorize">

    <div class="form-group">
        <label class="label secondary" for="email">Email:</label>
        <input type="email" name="email">

        <label class="label secondary" for="password">Password:</label>
        <input type="password" name="password">

    </div>

    <button type="submit" class="button primary">Authorize</button>

</form>
