<?php if( Session::getInstance()->isLoggedIn() &&
    $post->getUserid()==Session::getInstance()->getUser()->id): ?>
<a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete posts (and all likes and comments</a><br />
<?php endif; ?>

<cite><?= htmlspecialchars($post->getUser()) ?></cite>  <?php echo $post->date ?>
<h3><?= $post->getContent() ?></h3> Likes: <?php echo $post->getLikes() ?>

<hr>

<h3>Comments</h3>
<?php if( Session::getInstance()->isLoggedIn() ): ?>

    <form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

        <div class="form-group">
            <label for="content">New comment</label>
            <input id="content" name="content">
        </div>

        <button type="submit" class="btn btn-primary">Save</button>

    </form>
<?php endif; ?>
<?php foreach ($post->getComments() as $comment): ?>
    <div class="indent">
        <p>
            <cite><?= htmlspecialchars($comment->user) ?></cite>
            <?php echo $comment->date ?><br/>
            <?php echo $comment->content ?>
        </p>
        <?php if (Session::getInstance()->isLoggedIn()): ?>
            <a href="javascript:void(0);" class="comForm">Comment</a>
            <form method="post" action="<?= App::config('url') ?>admin/commentComment/<?php echo $comment->id ?>"
                  class="form-horizontal showActionComment">
                <input type="text" name="content">
            </form>
        <?php endif; ?>
        <?php Comment::recursion($comment->id) ?>
    </div>
<?php endforeach; ?>